name: Feature request
description: Suggest an idea or a new use case
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the use case first, then the solution you have in mind.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      render: python
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'd like to open a pull request for this
